### ISSUE TITLE
BLAKE2b support for JavaScript

### ISSUE THREAD

**Issue by neheb** [dchest/blake2s-js#1]
I tried adding this but it looks like I was unsuccessful as the output does not match b2sum even though your implementation of BLAKE2s does. Anyway, here's my attempt: https://github.com/neheb/blake2s-js/commit/deaa1e7704b8902e30ddd18798bd4fa49223a2bc

Any plans to support it?

**Comment by mdp** [comment]
In case anyone runs across this issue looking for Blake2b in pure js, I just found this guys implementation: https://github.com/dcposch/blakejs

**Comment by dchest** [comment]
@mdp thanks, I've just put a link from README to it.
