### ISSUE TITLE
Feature request: blake2xs

### ISSUE THREAD

**Issue by paulg446** [dchest/blake2s-js#7]
I noticed you implemented blake2xs in Go, any plans for a javascript implementation to compliment your fantastic javascript blake2s work?

**Comment by dchest** [comment]
Yes, it's included in [StableLib](https://www.stablelib.com), where most of my JavaScript work is not concentrated. `npm install @stablelib/blake2xs`. I'll link to it from README once StableLib is... stable :)

**Comment by paulg446** [comment]
Wow - great!  I had no idea about StableLib - looks incredible!

**Comment by dchest** [comment]
Thanks :) Yeah, I only recently published it, and will work on it more.
